v0.7 update

diff --git a/knoxsser b/knoxsser
--- a/knoxsser
+++ b/knoxsser
@@ -8,15 +8,15 @@ BOLD='\033[1m'
 NC='\033[0m'
 
 print_banner() {
-echo ""
-echo -e "${CYAN}██╗  ██╗███╗   ██╗ ██████╗ ██╗  ██╗███████╗███████╗███████╗██████╗  ${NC}"
-echo -e "${CYAN}██║ ██╔╝████╗  ██║██╔═══██╗╚██╗██╔╝██╔════╝██╔════╝██╔════╝██╔══██╗ ${NC}"
-echo -e "${CYAN}█████╔╝ ██╔██╗ ██║██║   ██║ ╚███╔╝ ███████╗███████╗█████╗  ██████╔╝ ${NC}"
-echo -e "${CYAN}██╔═██╗ ██║╚██╗██║██║   ██║ ██╔██╗ ╚════██║╚════██║██╔══╝  ██╔══██╗ ${NC}"
-echo -e "${CYAN}██║  ██╗██║ ╚████║╚██████╔╝██╔╝ ██╗███████║███████║███████╗██║  ██║ ${NC}"
-echo -e "${CYAN}╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝v0.6 ${NC}"
-echo -e "${BOLD}                                        Made with ${RED}<3${NC} by @0xPugal    ${NC}   "
-echo -e ""
+    echo ""
+    echo -e "${CYAN}██╗  ██╗███╗   ██╗ ██████╗ ██╗  ██╗███████╗███████╗███████╗██████╗  ${NC}"
+    echo -e "${CYAN}██║ ██╔╝████╗  ██║██╔═══██╗╚██╗██╔╝██╔════╝██╔════╝██╔════╝██╔══██╗ ${NC}"
+    echo -e "${CYAN}█████╔╝ ██╔██╗ ██║██║   ██║ ╚███╔╝ ███████╗███████╗█████╗  ██████╔╝ ${NC}"
+    echo -e "${CYAN}██╔═██╗ ██║╚██╗██║██║   ██║ ██╔██╗ ╚════██║╚════██║██╔══╝  ██╔══██╗ ${NC}"
+    echo -e "${CYAN}██║  ██╗██║ ╚████║╚██████╔╝██╔╝ ██╗███████║███████║███████╗██║  ██║ ${NC}"
+    echo -e "${CYAN}╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝v0.7 ${NC}"
+    echo -e "${BOLD}                                        Made with ${RED}<3${NC} by @0xPugal    ${NC}"
+    echo ""
 }
 
 if [[ $# -eq 0 ]]; then
@@ -29,7 +29,7 @@ input_type="file"
 input_file=""
 api_key="YOUR_KNOXSS_API_KEY"
 output_file="xss.txt"
-VERSION="v0.6"
+VERSION="v0.7"
 silent_mode=false
 use_notify=false
 
@@ -46,6 +46,7 @@ usage() {
     exit 1
 }
 
+# Parsing command-line arguments
 while [[ $# -gt 0 ]]; do
     key="$1"
     case $key in
@@ -77,7 +78,7 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         -n|--notify)
-            use_notify=true  # Set the flag to true
+            use_notify=true  
             shift
             ;;
         -v|--version)
@@ -89,11 +90,12 @@ while [[ $# -gt 0 ]]; do
             ;;
         *)
             echo "Error: Unknown option: $1"
-            exit 0
+            usage
             ;;
     esac
 done
 
+# Validations for required arguments
 if [[ "$input_type" == "file" && -z "$input_file" ]]; then
     echo "Error: Input file not specified"
     usage
@@ -102,6 +104,7 @@ elif [[ "$input_type" == "url" && -z "$single_url" ]]; then
     usage
 fi
 
+# Set up URLs for scanning based on input type
 if [[ "$input_type" == "file" ]]; then
     sed -i 's/&/%26/g' "$input_file"
     urls_file="$input_file"
@@ -110,13 +113,15 @@ else
     echo "$single_url" > "$urls_file"
 fi
 
+# Function to handle Ctrl-C interruptions
 handle_ctrl_c() {
-    echo -e "\nCtrl-C detected. remaining URLs are saved into $todo_file..."
+    echo -e "\nCtrl-C detected. Remaining URLs are saved into $todo_file..."
     sed -n "${lineno},\$p" "$urls_file" > "$todo_file"
     echo "Total API calls made: $api_calls"
     exit 1
 }
 
+# Set up Ctrl-C handler
 trap handle_ctrl_c INT
 
 lineno=1
@@ -124,57 +129,78 @@ api_calls=0
 todo_file="${urls_file%.*}-$(date +'%Y%m%d%H%M%S').todo"
 error_url="${urls_file%.*}-errors.todo"
 
+# Display banner unless in silent mode
 if ! $silent_mode; then
     print_banner
 fi
 
-while read line; do
-    response=$(curl https://api.knoxss.pro -d target="$line" -H "X-API-KEY: $api_key" -s)
-    xss=$(jq -r '.XSS' <<< "$response")
-    poc=$(jq -r '.PoC' <<< "$response")
-    error=$(jq -r '.Error' <<< "$response")
-    api_call=$(jq -r '.["API Call"]' <<< "$response")
+# Check for a valid API key
+test_response=$(curl "https://api.knoxss.pro" -d target="https://example.com" -H "X-API-KEY: $api_key" -s)
 
-    if [[ "$xss" == "true" ]]; then
-        echo -e "${GREEN}[XSS!] - $poc ${NC} [$api_call]"
-        echo "$response" >> "$output_file"
+if [[ "$test_response" == "Invalid or expired API key." ]]; then
+    echo -e "${RED}Invalid or expired API key. Exiting.${NC}"
+    exit 1
+fi
 
-        if  [[ "$use_notify" == true ]]; then
-                echo "$poc" | notify -silent > /dev/null 2>&1 
-                if [[ "$api_call" != "0" ]]; then
-                        api_calls=$((api_calls + 1))
-                fi
-        fi
+# Main loop to scan URLs
+while read -r line; do
+    response=$(curl "https://api.knoxss.pro" -d target="$line" -H "X-API-KEY: $api_key" -s)
 
-    elif [[ "$xss" == "false" ]]; then
-        echo -e "${YELLOW}[No XSS] - $line${NC} [$api_call]"
-        if [[ "$api_call" != "0" ]]; then
-            api_calls=$((api_calls + 1))
-        fi
-
-    elif [[ "$error" == "KNOXSS can't test it (forbidden)" ]]; then
-        echo -e "${RED}[ERR] - $line - Forbidden ${NC} [$api_call]"
-
-    elif [[ "$error" == "Content type of target page can't lead to XSS!" ]]; then
-        echo -e "${RED}[ERR] - $line - XSS not possible ${NC} [$api_call]"
-
-    elif [[ "$error" == "target connection issues (timeout)" ]]; then
-        echo -e "${RED}[ERR] - $line - Target connection issues ${NC} [$api_call]"
-
-    elif [[ "$error" == "KNOXSS can't finish scan gracefully (reason unknown)" ]]; then
-        echo -e "${RED}[ERR] - $line - can't finish scan gracefully${NC} [$api_call]"
+    if [[ "$response" == *"Invalid or expired API key."* ]]; then
+        echo -e "${RED}Invalid or expired API key. Exiting.${NC}"
+        exit 1
+    
+    elif [[ "$response" == *"<p"* ]]; then
+            echo -e "${RED}[ERR] - $line - XSS is not possible in this content-type${NC} [$api_call]"
 
     else
-        echo -e "${RED}[ERR] - $line - KNOXSS ERROR(Unknown) ${NC} [$api_call]"
-        echo "$line" >> "$error_url"
+        xss=$(jq -r '.XSS' <<< "$response")
+        poc=$(jq -r '.PoC' <<< "$response")
+        error=$(jq -r '.Error' <<< "$response")
+        api_call=$(jq -r '.["API Call"]' <<< "$response")
+
+        # Handle XSS detection
+        if [[ "$xss" == "true" ]]; then
+            echo -e "${GREEN}[XSS!] - $poc ${NC} [$api_call]"
+            echo "$response" >> "$output_file"
+
+            if [[ "$use_notify" == true ]]; then
+                echo "$poc" | notify -silent > /dev/null 2>&1 
+                if [[ "$api_call" != "0" ]]; then
+                    api_calls=$((api_calls + 1))
+                fi
+            fi
+
+        elif [[ "$xss" == "false" ]]; then
+            echo -e "${YELLOW}[No XSS] - $line ${NC} [$api_call]"
+            if [[ "$api_call" != "0" ]]; then
+                api_calls=$((api_calls + 1))
+            fi
+        
+        elif [[ "$error" == "KNOXSS can't test it (forbidden)" ]]; then
+        echo -e "${RED}[ERR] - $line - Forbidden ${NC} [$api_call]"
+
+        elif [[ "$error" == "target connection issues (timeout)" ]]; then
+        echo -e "${RED}[ERR] - $line - Target connection issues ${NC} [$api_call]"
+
+        elif [[ "$error" == "KNOXSS can't finish scan gracefully (reason unknown)" ]]; then
+        echo -e "${RED}[ERR] - $line - can't finish scan gracefully${NC} [$api_call]"
+
+        else
+            echo -e "${RED}[ERR] - Unknown error ${NC} [$api_call]"
+            echo "$line" >> "$error_url"
+        fi
     fi
-    sleep 2
+
+    sleep 2  # Delay between API calls to avoid rate limiting
     lineno=$((lineno + 1))
 done < "$urls_file"
 
-echo "URLs which encountered error are saved into $error_url"
+# Final summary
+echo "If any URLs that encountered errors are saved into $error_url"
 echo "Total API calls made: $api_calls"
 
+# Cleanup temporary files if needed
 if [[ "$input_type" == "url" ]]; then
     rm "$urls_file"
 fi
